"""
Django settings for sitio project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv
if os.environ.get('DEBUG', 'True') == 'True':
    load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')

if not DEBUG and '.onrender.com' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('.onrender.com')



# Application definition

INSTALLED_APPS = [
    'unfold',
    "unfold.contrib.filters", 
    "unfold.contrib.forms",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'reportes',
    'storages',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sitio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sitio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True
        )
    }

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', '127.0.0.1'),
            'PORT': os.getenv('DB_PORT', '3306'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#3.Configuración de Azure Blob Storage
AZURE_ACCOUNT_NAME = os.getenv('AZURE_ACCOUNT_NAME')
AZURE_CONTAINER = os.getenv("AZURE_CONTAINER_NAME") 
AZURE_CONNECTION_STRING = os.getenv("AZURE_STORAGE_CONNECTION_STRING") 
DEFAULT_FILE_STORAGE = 'reportes.storage_backends.AzureMediaStorage'

AZURE_CUSTOM_DOMAIN = f'{AZURE_ACCOUNT_NAME}.blob.core.windows.net'
MEDIA_URL = f'https://{AZURE_CUSTOM_DOMAIN}/{AZURE_CONTAINER}/'

LOGIN_URL = 'login'  # Usa el nombre de la URL, no la ruta
LOGIN_REDIRECT_URL = 'home'  # Redirige a home después del login
LOGOUT_REDIRECT_URL = 'login'  # Redirige a login después del logout

# Configuración de sesión (opcional pero recomendado)
SESSION_COOKIE_AGE = 3600  # Sesión expira en 1 hora (3600 segundos)
SESSION_SAVE_EVERY_REQUEST = True  # Renueva el tiempo de sesión en cada request
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Sesión expira al cerrar navegador

from pathlib import Path
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _

# Configuración de Unfold
UNFOLD = {
    # Información general del sitio
    "SITE_TITLE": "Sistema de Reportes ECVA",
    "SITE_HEADER": "Panel de Administración de Reportes",
    "SITE_URL": "/",
    
    # Logos e íconos
    "SITE_LOGO": {
        "light": lambda request: static("images/logo-ECVA.png"),
        "dark": lambda request: static("images/logo-ECVA.png"),
    },
    "SITE_ICON": {
        "light": lambda request: static("images/logo-ECVA.png"),
        "dark": lambda request: static("images/logo-ECVA.png"),
    },
    "SITE_FAVICON": lambda request: static("images/logo-ECVA.png"),
    
    "SITE_SYMBOL": "speed",  
    
    # Estilos personalizados
    "STYLES": [
        lambda request: static("css/custom_styles.css"),
    ],
    
    # Esquema de colores
    "COLORS": {
        "primary": {
            "50": "#ffeaea",
            "100": "#ffc7c7",
            "200": "#ff9e9e",
            "300": "#ff7676",
            "400": "#ff4d4d",
            "500": "#fe2020",
            "600": "#e61c1c",
            "700": "#cc1818",
            "800": "#b31414",
            "900": "#991010"
        },
    },
    
    
    "THEME": "light", 
    
    # Sidebar (barra lateral)
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": _("Navegación"),
                "separator": True,
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": lambda request: "/admin/",
                    },
                ],
            },
            {
                "title": _("Catálogos"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Categorías"),
                        "icon": "category",
                        "link": lambda request: "/admin/reportes/categoria/",
                    },
                    {
                        "title": _("Disponibilidad"),
                        "icon": "check_circle",
                        "link": lambda request: "/admin/reportes/disponibilidad/",
                    },
                    {
                        "title": _("Categoría Daño"),
                        "icon": "warning",
                        "link": lambda request: "/admin/reportes/categoriadano/",
                    },
                    {
                        "title": _("Roles"),
                        "icon": "badge",
                        "link": lambda request: "/admin/reportes/rol/",
                    },
                ],
            },
            {
                "title": _("Gestión de Personal"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Empleados"),
                        "icon": "person",
                        "link": lambda request: "/admin/reportes/empleado/",
                    },
                    {
                        "title": _("Transportistas"),
                        "icon": "local_shipping",
                        "link": lambda request: "/admin/reportes/usuariotransportista/",
                    },
                ],
            },
            {
                "title": _("Proyectos"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Clientes"),
                        "icon": "people",
                        "link": lambda request: "/admin/reportes/cliente/",
                    },
                    {
                        "title": _("Obras"),
                        "icon": "construction",
                        "link": lambda request: "/admin/reportes/obras/",
                    },
                    {
                        "title": _("Piezas"),
                        "icon": "inventory_2",
                        "link": lambda request: "/admin/reportes/piezas/",
                    },
                ],
            },
            {
                "title": _("Reportes"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Reporte de Daño"),
                        "icon": "report_problem",
                        "link": lambda request: "/admin/reportes/reportedano/",
                    },
                    {
                        "title": _("Piezas Rechazadas"),
                        "icon": "block",
                        "link": lambda request: "/admin/reportes/piezarechazada/",
                    },
                ],
            },
            {
                "title": _("Administración"),
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": _("Usuarios"),
                        "icon": "people",
                        "link": lambda request: "/admin/auth/user/",
                    },
                    {
                        "title": _("Grupos"),
                        "icon": "groups",
                        "link": lambda request: "/admin/auth/group/",
                    },
                ],
            },
        ],
    },
    
    # Configuración de tabs
    "TABS": [
        {
            "models": [
                "reportes.reportedano",
                "reportes.piezarechazada",
            ],
            "items": [
                {
                    "title": _("Reportes de Daño"),
                    "link": lambda request: "/admin/reportes/reportedano/",
                },
                {
                    "title": _("Piezas Rechazadas"),
                    "link": lambda request: "/admin/reportes/piezarechazada/",
                },
            ],
        },
    ],
}



            
            
        