# Generated by Django 5.2.5 on 2025-08-26 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaDano',
            fields=[
                ('idCategoriaDano', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('idDisponibilidad', models.AutoField(primary_key=True, serialize=False)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('idObra', models.AutoField(primary_key=True, serialize=False)),
                ('nombreObra', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('puesto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioTransportista',
            fields=[
                ('idConductor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('patente', models.CharField(max_length=50)),
                ('transporte', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('domicilio', models.CharField(max_length=255)),
                ('idObra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.obras')),
            ],
        ),
        migrations.CreateModel(
            name='Piezas',
            fields=[
                ('idPieza', models.AutoField(primary_key=True, serialize=False)),
                ('medidas', models.CharField(max_length=100)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.categoria')),
                ('idDisponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.disponibilidad')),
            ],
        ),
        migrations.CreateModel(
            name='PiezaRechazada',
            fields=[
                ('idPiezaRechazada', models.AutoField(primary_key=True, serialize=False)),
                ('observaciones', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('imagenURL', models.URLField()),
                ('idCategoriaDano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.categoriadano')),
                ('idPieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.piezas')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.rol')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteDano',
            fields=[
                ('idReporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('remitoRecepcion', models.CharField(max_length=255)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.cliente')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.empleado')),
                ('idPiezaRechazada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.piezarechazada')),
                ('idConductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.usuariotransportista')),
            ],
        ),
    ]
