# Generated by Django 5.2.5 on 2025-09-11 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedano',
            name='idPiezaRechazada',
        ),
        migrations.AddField(
            model_name='piezarechazada',
            name='idReporte',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reportes.reportedano'),
            preserve_default=False,
        ),
    ]
