# Generated by Django 5.2.5 on 2025-09-16 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_remove_reportedano_idpiezarechazada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='idObra',
        ),
        migrations.AddField(
            model_name='obras',
            name='idCliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reportes.cliente'),
            preserve_default=False,
        ),
    ]
