# Generated by Django 5.2.5 on 2025-09-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0003_remove_cliente_idobra_obras_idcliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedano',
            name='remitoRecepcion',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
