# Generated by Django 5.2.5 on 2025-09-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_alter_reportedano_remitorecepcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piezarechazada',
            name='imagenURL',
        ),
        migrations.AddField(
            model_name='piezarechazada',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='piezas_rechazadas/'),
        ),
    ]
