# Generated by Django 5.2.5 on 2025-10-09 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0005_remove_piezarechazada_imagenurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedano',
            name='idObra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reportes.obras'),
        ),
    ]
