# Generated by Django 5.2.5 on 2025-10-09 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0008_reportedano_idobra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedano',
            name='idObra',
        ),
    ]
