# Generated by Django 5.2.5 on 2025-10-09 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0009_remove_reportedano_idobra'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedano',
            name='idObra',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='reportes.obras'),
            preserve_default=False,
        ),
    ]
