# Generated by Django 5.2.5 on 2025-10-19 15:40

import reportes.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0010_reportedano_idobra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piezarechazada',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=reportes.storage_backends.AzureMediaStorage(), upload_to='piezas_rechazadas/'),
        ),
    ]
